### ISSUE TITLE
Plzz solve this error

### ISSUE THREAD

**Issue by NickxFury** [reaitten/tk#16]
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by reaitten** [comment]
send bulid log.

**Comment by NickxFury** [comment]
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

This msg ☝️ shows during the deployment and the build was not succesfull

**Comment by AmirulAndalib** [comment]
@reaitten  come to telegram need to discuss some important stuff...

https://t.me/kensur99

pls 🙏

**Comment by NickxFury** [comment]
> > There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.
> > This msg ☝️ shows during the deployment and the build was not succesfull
> 
> ok looking into dis

Okk!

**Comment by reaitten** [comment]
i can't recreate the issue, can you try again deploying again?

![image](https://user-images.githubusercontent.com/52531973/117501021-7d07c000-af4b-11eb-9a77-f73df61bf54f.png)

**Comment by NickxFury** [comment]
> i can't recreate the issue, can you try again deploying again?
> 
> ![image](https://user-images.githubusercontent.com/52531973/117501021-7d07c000-af4b-11eb-9a77-f73df61bf54f.png)

After ur new commit the bot successfully deployed.

**Comment by NickxFury** [comment]
> i can't recreate the issue, can you try again deploying again?
> 
> ![image](https://user-images.githubusercontent.com/52531973/117501021-7d07c000-af4b-11eb-9a77-f73df61bf54f.png)

ValueError: Cannot get entity by phone number as a bot (try using integer IDs, not strings)

What is this error I entered correct id and owner id of admins but when I give start msg this msg shows ☝

**Comment by NickxFury** [comment]
> > i can't recreate the issue, can you try again deploying again?
> > ![image](https://user-images.githubusercontent.com/52531973/117501021-7d07c000-af4b-11eb-9a77-f73df61bf54f.png)
> 
> ValueError: Cannot get entity by phone number as a bot (try using integer IDs, not strings)
> 
> What is this error I entered correct id and owner id of admins but when I give start msg this msg shows ☝

![Screenshot_2021-05-08-02-00-09-840_com android chrome](https://user-images.githubusercontent.com/73124813/117505165-3cd32c80-afa1-11eb-89


> > i can't recreate the issue, can you try again deploying again?
> > ![image](https://user-images.githubusercontent.com/52531973/117501021-7d07c000-af4b-11eb-9a77-f73df61bf54f.png)
> 
> After ur new commit the bot successfully deployed.

![IMG_20210508_020300_989](https://user-images.githubusercontent.com/73124813/117505449-ac491c00-afa1-11eb-88b1-d0aca6e32a6c.jpg)

**Comment by reaitten** [comment]
redeploy again. please note that uploading to tg doesn't work.

**Comment by NickxFury** [comment]
> redeploy again with latest commit. please note that uploading to tg doesn't work.

Then how to use it as a leech bot 🧐

**Comment by AmirulAndalib** [comment]
> > redeploy again with latest commit. please note that uploading to tg doesn't work.
> 
> Then how to use it as a leech bot 🧐

this is in beta unstable stage as we already told before we are looking for contributors who can help us remove the blocks from the bot..........

**Comment by NickxFury** [comment]
Ok ok ! i know I just asked when it will be in stable to use.
