### ISSUE TITLE
Unable to upload files.

### ISSUE THREAD

**Issue by hackevil** [reaitten/tk#19]
Deployed it successfully on heroku, but whenever i try to leech a torrent or direct link, it downloads it successfully but never uploads it to Gdrive or Telegram. It only shows "Trying to upload" when a direct link is leeched and shows "Download completed xyz  to path /tk/Downloads/16205762876410944/".
 
I have attached a log and screenshot.
![Capture](https://user-images.githubusercontent.com/23115256/117579096-0ca99c00-b10f-11eb-8a1f-770d862560ca.PNG)

https://del.dog/lerulaseri.txt

**Comment by reaitten** [comment]
redeploy with newest commit, everything should be working now. thanks for the heads up!
